test

diff --git a/task/sast-snyk-check/0.3/sast-snyk-check.yaml b/task/sast-snyk-check/0.3/sast-snyk-check.yaml
--- a/task/sast-snyk-check/0.3/sast-snyk-check.yaml
+++ b/task/sast-snyk-check/0.3/sast-snyk-check.yaml
@@ -125,7 +125,7 @@ spec:
         # In order to generate csdiff/v1, we need to add the whole path of the source code as Snyk only provides an URI to embed the context
         set -x
         csgrep --prepend-path-prefix="$SOURCE_CODE_DIR"/ sast_snyk_check_out.json | csgrep --embed-context 3 | csgrep --strip-path-prefix="$SOURCE_CODE_DIR"/source/  > sast_snyk_check_out_all_findinds.txt
-        csgrep --mode=json --prepend-path-prefix="$SOURCE_CODE_DIR"/ sast_snyk_check_out.json | csgrep --mode=sarif --embed-context 3 | csgrep --mode=sarif --strip-path-prefix="$SOURCE_CODE_DIR"/source/  > sast_snyk_check_out_all_findinds.json
+        csgrep --mode=json --prepend-path-prefix="$SOURCE_CODE_DIR"/ sast_snyk_check_out.json | csgrep --mode=sarif --embed-context 3 | csgrep --mode=sarif --strip-path-prefix="$SOURCE_CODE_DIR"/source/  > sast_snyk_check_out_all_findings.json
         cat sast_snyk_check_out_all_findinds.txt
         cat sast_snyk_check_out_all_findinds.json
         set +x
@@ -134,8 +134,13 @@ spec:
         set -x
         echo $KFP_GIT_URL
         csfilter-kfp --version
-        csfilter-kfp --verbose --kfp-git-url=$KFP_GIT_URL sast_snyk_check_out_all_findinds.json > sast_snyk_check_out.sarif
-        cat sast_snyk_check_out.sarif
+        csfilter-kfp --verbose --kfp-git-url=$KFP_GIT_URL sast_snyk_check_out_all_findings.json > filtered_sast_snyk_check_out.json
+        TEST_OUTPUT=
+          parse_test_output $(context.task.name) sarif sast_snyk_check_out.json  || true
+        
+        note="Task $(context.task.name) failed: For details, check Tekton task log."
+        ERROR_OUTPUT=$(make_result_json -r ERROR -t "$note")
+        echo "${TEST_OUTPUT:-${ERROR_OUTPUT}}" | tee $(results.TEST_OUTPUT.path)
         set +x
 
     - name: upload
